name: Build
on:
  push:
    branches:
      - master # or the name of your main branch
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: 2348b94161c4959ca08dc1d9f4e89faf861ce305
          SONAR_HOST_URL: https://fbdf-2406-7400-9d-c8d6-6064-9bcc-76ce-5769.ngrok.io
      
