name: Deploy to Elastic Beanstalk
on:
  push:
    branches:
      - dev
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Generate deployment package
        run: zip -r deploy.zip * .[^.]* -x "**node_modules**"
      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v15
        with:
           version_label: v1.12
           version_description: This is version v1.12
      - name: Get current version
        id: get_version
        run: |
          VERSION=$(grep -oP 'version_label:\s*\Kv\d+\.\d+' \.github\workflows\deploy.yml)
          echo "::set-output name=version::$VERSION"
      - name: Increment version
        id: increment_version
        run: |
          PREVIOUS_VERSION=${{ steps.get_version.outputs.version }}
          MAJOR=$(echo "$PREVIOUS_VERSION" | grep -oP 'v\K\d+')
          MINOR=$(echo "$PREVIOUS_VERSION" | grep -oP '\.\K\d+')
          NEW_VERSION="v$((MAJOR)).$((MINOR + 1))"
          echo "::set-output name=new_version::$NEW_VERSION"
      - name: Update version_label
        run: |
          sed -i "s/version_label:.*/version_label: ${{ steps.increment_version.outputs.new_version }}/" \.github\workflows\deploy.yml
